### ISSUE TITLE
At the end crashes 

### ISSUE THREAD

**Issue by Guffy31** [elebumm/RedditVideoMakerBot#1008] opened 2022-07-16 03:59 UTC
When is doing a specific thred at the it crashes, for it does it whit "Without saying the name, what's your favorite video game?" thats the one that makes it crash at the end.
![Captura de pantalla 2022-07-15 235345](https://user-images.githubusercontent.com/109401612/179338407-57f042f6-e381-4d1a-a1ce-36290cfdab3a.png)

**Comment by LiamGallagher737** [comment] 2022-07-16 06:42
I'm also getting the same error and only on that reddit thread #1006

**Comment by micziz** [comment] 2022-07-16 08:50
A response is in #1006

**Comment by JasonLovesDoggo** [comment] 2022-07-18 04:26
Duplicate of #1006

**Closed by JasonLovesDoggo** 2022-07-18 04:26 UTC
Labels: bug
