### ISSUE TITLE
Add a content filter that changes words like kill or other TOS unfriendly words to tos friendly words

### ISSUE THREAD

**Issue by BoomSec** [elebumm/RedditVideoMakerBot#654] opened 2022-06-22 13:57 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered** (optional)

**Additional context** (optional)

**Comment by sadmoonphoenix** [comment] 2022-06-22 16:50
Duplicate of https://github.com/elebumm/RedditVideoMakerBot/issues/407. Also fixed by pending PR, https://github.com/elebumm/RedditVideoMakerBot/pull/447. Please close this issue.

**Closed** 2022-07-20 02:36 UTC
Labels: enhancement
