### ISSUE TITLE
Crash on some titles

### ISSUE THREAD

**Issue by Schweinhitti** [elebumm/RedditVideoMakerBot#392] opened 2022-06-08 18:37 UTC
The bot crashes on some posts like this one

https://www.reddit.com/r/AskReddit/comments/v7q4bq/whats_one_showmovie_that_you_just_refuse_to_watch/

**Comment by JasonLovesDoggo** [comment] 2022-06-12 18:14
Duplicate of #391

**Closed by JasonLovesDoggo** 2022-06-12 18:14 UTC
