### ISSUE TITLE
Continue previous thread

### ISSUE THREAD

**Issue by dasbts** [elebumm/RedditVideoMakerBot#925] opened 2022-07-09 17:24 UTC
**Is your feature request related to a problem? Please describe.**
The bot currently takes a thread, takes some comments and then kind of blacklists it in videos.json to ever be checked again.

**Describe the solution you'd like**
I would suggest the possibility to check for new comments, thus allowing continuing rendering videos from a previous thread. This would probably require to save the comment ID as well in the videos.json, but to implement that it would require migration which means adding something to check in videos.json if comment_id exists, and if not to add an empty ID or placeholder. 

This way, popular topics can be revisited for continuous content and to not miss out on important comments. I would however suggest it to always read the title even if it's continued, could of course also add title+"continued" in the TTS. 

I have searched the repo issues but couldn't find a similar suggestion, hopefully I haven't missed any similar ones.

**Comment by JasonLovesDoggo** [comment] 2022-07-10 01:42
I'm on data so I won't bother finding the one that this is a duplicate of but this is a duplicate

**Closed by JasonLovesDoggo** 2022-07-10 01:42 UTC
Labels: enhancement
