### ISSUE TITLE
getting this error help 

### ISSUE THREAD

**Issue by shubh-3011** [elebumm/RedditVideoMakerBot#221] opened 2022-06-03 17:29 UTC
![image](https://user-images.githubusercontent.com/81286735/171916054-2781de6f-34aa-4955-8961-9fbcb5838ea9.png)

**Comment by CallumIO** [comment] 2022-06-03 17:35
Duplicate of #200, I've answered there.

**Closed by CallumIO** 2022-06-03 17:35 UTC
