### ISSUE TITLE
LONG posts + no comments when subreddit isn't AskReddit

### ISSUE THREAD

**Issue by gBlaku** [elebumm/RedditVideoMakerBot#376] opened 2022-06-07 19:48 UTC
When I use any subreddit except for AskReddit, my videos often end up upwards of 7 minutes long and with no comments. Anyone else experience this?

**Comment by OGreeni** [comment] 2022-06-08 00:08
What subreddit, specifically?

**Comment by gBlaku** [comment] 2022-06-08 03:59
> What subreddits, specifically?

One for example: tifu

**Comment by iaacornus** [comment] 2022-06-08 04:12
perhaps the selected thread has no comments?

**Comment by DrMxrcy** [comment] 2022-06-08 12:24
Another one is nosleep

**Comment by gBlaku** [comment] 2022-06-08 19:25
Really hoping a fix comes out

**Comment by CallumIO** [comment] 2022-06-22 20:58
Duplicate of many others

**Closed by CallumIO** 2022-06-22 20:58 UTC
