### ISSUE TITLE
I followed the instructions of the book and am stuck here

### ISSUE THREAD

**Issue by dehfguiefhjen** [elebumm/RedditVideoMakerBot#775] opened 2022-07-01 05:50 UTC
![Screenshot (2)](https://user-images.githubusercontent.com/108509491/176832051-953f009a-f40b-45fa-8bbf-1854ea094ec7.png)

**Comment by dehfguiefhjen** [comment] 2022-07-01 05:53
![Screenshot (3)](https://user-images.githubusercontent.com/108509491/176832401-2f184cac-1bb9-40ee-b6dd-708e16b541b7.png)

**Comment by dehfguiefhjen** [comment] 2022-07-01 05:55
![Uploading Screenshot (3).png…]()

**Comment by dehfguiefhjen** [comment] 2022-07-01 05:55
![Screenshot (3)](https://user-images.githubusercontent.com/108509491/176832719-939f888b-477d-4135-8d8a-c003d3ba3ead.png)

**Comment by NHastings2** [comment] 2022-07-01 06:00
Hi @dehfguiefhjen, you wont need the username and password if you supply the client id and secret. Please try removing these and try again. If that doesn't work. Also make sure that there is no space between REDDIT_CLIENT_ID and the quotation marks (i.e. REDDIT_CLIENT_ID=""). Please let me know if this works.

**Comment by dehfguiefhjen** [comment] 2022-07-01 06:03
> Hi @dehfguiefhjen, you wont need the username and password if you supply the client id and secret. Please try removing these and try again. If that doesn't work. Also make sure that there is no space between REDDIT_CLIENT_ID and the quotation marks (i.e. REDDIT_CLIENT_ID=""). Please let me know if this works.

I did both and neither worked, I didnt delete the lines of REDDIT_USERNAME= "" but I left them blank that could be the issue?

**Comment by dehfguiefhjen** [comment] 2022-07-01 06:05
Tried removing them entirely didnt work either

**Comment by NHastings2** [comment] 2022-07-01 06:09
Just for verification, you have the .env file in the same directory as the main.py file right?

**Comment by dehfguiefhjen** [comment] 2022-07-01 06:12
yea

**Comment by dehfguiefhjen** [comment] 2022-07-01 06:12
![Screenshot (4)](https://user-images.githubusercontent.com/108509491/176834965-dd633462-8512-4e5f-bf9a-ae465a2c660f.png)

**Comment by NHastings2** [comment] 2022-07-01 06:19
I see what the problem is. In the windows file explorer, click on view  (in the top left), and then select Show File Extensions. The problem is that the .env file is still .env.template so its not seeing it. If you show file name extensions, you can remove the .template and then the script will recognize it and load the variables.

**Comment by dehfguiefhjen** [comment] 2022-07-01 06:21
it works now ty :)

**Comment by dehfguiefhjen** [comment] 2022-07-01 06:22
wait nvm

**Comment by dehfguiefhjen** [comment] 2022-07-01 06:22
![Screenshot (6)](https://user-images.githubusercontent.com/108509491/176836326-09e17c13-7ae3-4336-9de3-f71f1628609e.png)
![Screenshot (5)](https://user-images.githubusercontent.com/108509491/176836337-7e69e455-0ab3-4b6c-b02b-f1460df5192e.png)

**Comment by dehfguiefhjen** [comment] 2022-07-01 06:22
![Screenshot (5)](https://user-images.githubusercontent.com/108509491/176836403-6d49315e-516c-4b0d-b70c-e52b9534f405.png)
![Screenshot (6)](https://user-images.githubusercontent.com/108509491/176836413-fddb7a1f-7039-4502-91b3-f6273a7af23e.png)

**Comment by NHastings2** [comment] 2022-07-01 06:24
Recently the creator of the TTS site added a rate limit to the AWS server. After about 20 request, there is a 60 second wait before you can submit more requests. I'm currently working on a patch that will add a wait when the rate is reached so that longer comment threads can be reached. This is also related #772, #768, and #767 for reference.

**Comment by Cizzl** [comment] 2022-07-01 06:25
Fixed in develop

**Comment by dehfguiefhjen** [comment] 2022-07-01 06:25
> Fixed in develop

Do i redownload the new version?

**Comment by NHastings2** [comment] 2022-07-01 06:29
> Fixed in develop

@Cizzl When was it added to develop? I didn't notice it anywhere.

**Comment by dehfguiefhjen** [comment] 2022-07-01 06:31
> > Fixed in develop
> 
> @Cizzl When was it added to develop? I didn't notice it anywhere.

I dont see it either

**Comment by Cizzl** [comment] 2022-07-01 06:50
@NHastings2 it's in #691

**Comment by sarimwaniR** [comment] 2022-07-01 14:46
solved?

**Comment by dehfguiefhjen** [comment] 2022-07-01 17:09
![Screenshot (7)](https://user-images.githubusercontent.com/108509491/176939870-2862e760-1a2f-4223-bb32-f744a23ba230.png)

**Comment by dehfguiefhjen** [comment] 2022-07-01 17:11
I did that and it fixed the previous issue but now I cant run playwright. Whenever i run playwright install it returns that, and just before this i did "python3 -m pip install --force-reinstall playwright" and reinstalled it hoping that would fix the issue but it didnt

**Comment by JasonLovesDoggo** [comment] 2022-07-01 23:55
fixed in 2.2

**Closed by JasonLovesDoggo** 2022-07-01 23:55 UTC
