### ISSUE TITLE
Playwright error i think 

### ISSUE THREAD

**Issue by Zetronx0** [elebumm/RedditVideoMakerBot#344] opened 2022-06-06 16:26 UTC
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "[data-test-id="post-content"]"

it says that after taking screenshots

**Comment by ItaiDanos** [comment] 2022-06-06 23:04
I got the same issue

**Comment by susgsus** [comment] 2022-06-09 18:29
me 2

**Comment by ORI299** [comment] 2022-06-10 08:08
same

**Comment by DylanDelobel** [comment] 2022-06-10 18:31
Duplicate of #34

**Comment by FreebieII** [comment] 2022-06-10 18:34
Closing as duplicate of [34](https://github.com/elebumm/RedditVideoMakerBot/issues/34)

Happy Coding!

**Closed by FreebieII** 2022-06-10 18:34 UTC
