### ISSUE TITLE
[Bug]:  libespeak.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by diegooviedo3004** [elebumm/RedditVideoMakerBot#1723] opened 2023-06-26 17:10 UTC
### Describe the bug

Sorry, something went wrong with this version! Try again, and feel free to   │
│ report this issue at GitHub or the Discord community.                        │
│ Version: 3.2                                                                 │
│ Error: libespeak.so.1: cannot open shared object file: No such file or       │
│ directory                                                                    │
│ Config: {'allow_nsfw': False, 'theme': 'dark', 'times_to_run': 1, 'opacity': │
│ 0.9, 'storymode': False, 'storymodemethod': 1, 'storymode_max_length': 1000, │
│ 'resolution_w': 1080, 'resolution_h': 1920, 'zoom': 1, 'background':         │
│ {'background_video': 'minecraft', 'background_audio': 'lofi',                │
│ 'background_audio_volume': 0.15, 'enable_extra_audio': False,                │
│ 'background_thumbnail': False, 'background_thumbnail_font_family': 'arial',  │
│ 'background_thumbnail_font_size': 96, 'background_thumbnail_font_color':     │
│ '255,255,255'}, 'tts': {'voice_choice': 'pyttsx', 'random_voice': True,      │
│ 'elevenlabs_voice_name': 'Bella', 'elevenlabs_api_key': 'REDACTED',          │
│ 'aws_polly_voice': 'Matthew', 'streamlabs_polly_voice': 'Matthew',           │
│ 'tiktok_voice': 'en_us_001', 'tiktok_sessionid': 'REDACTED', 'python_voice': │
│ '1', 'py_voice_num': '2', 'silence_duration': 0.3, 'no_emojis': False}} 

### Reproduction Steps

Pretty sure it is enough with the description│ Config: {'allow_nsfw': False, 'theme': 'dark', 'times_to_run': 1, 'opacity': │
│ 0.9, 'storymode': False, 'storymodemethod': 1, 'storymode_max_length': 1000, │
│ 'resolution_w': 1080, 'resolution_h': 1920, 'zoom': 1, 'background':         │
│ {'background_video': 'minecraft', 'background_audio': 'lofi',                │
│ 'background_audio_volume': 0.15, 'enable_extra_audio': False,                │
│ 'background_thumbnail': False, 'background_thumbnail_font_family': 'arial',  │
│ 'background_thumbnail_font_size': 96, 'background_thumbnail_font_color':     │
│ '255,255,255'}, 'tts': {'voice_choice': 'pyttsx', 'random_voice': True,      │
│ 'elevenlabs_voice_name': 'Bella', 'elevenlabs_api_key': 'REDACTED',          │
│ 'aws_polly_voice': 'Matthew', 'streamlabs_polly_voice': 'Matthew',           │
│ 'tiktok_voice': 'en_us_001', 'tiktok_sessionid': 'REDACTED', 'python_voice': │
│ '1', 'py_voice_num': '2', 'silence_duration': 0.3, 'no_emojis': False}} 

### Expected behavior

Program just started well, and even it fetches the data from reddit Thread has 858 upvotes
Thread has a upvote ratio of 92.0%
Thread has 968 comments
Received subreddit threads Successfully.
Thread ID is 14jfxmu
I got stuck in Saving Text to MP3 files...

### System Information

Operating System : Linux Mint Cinnamon Edition
Python version : 3.10
App version / Branch : 

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

### Additional Context

If you guys can provide a config.toml that works, (of course, not including the script key and stuff), I would be grateful.

**Comment by rafaelsoley** [comment] 2023-06-27 16:50
This is caused by the TTS module (pyttsx3), choose another TTS module to fix the issue, for now…

Will be fixed on future update, hopefully.

**Comment by OpenSourceSimon** [comment] 2023-06-27 19:22
I guess this is using pyttsx3, maybe you don't have the voices downloaded since they aren't downloaded on default? Best to do is just use a different TTS provider

**Closed by OpenSourceSimon** 2023-06-27 19:22 UTC
Labels: bug
