### ISSUE TITLE
Changing render to horizontal video

### ISSUE THREAD

**Issue by tayzuz** [elebumm/RedditVideoMakerBot#707] opened 2022-06-25 21:15 UTC
**Is your feature request related to a problem? Please describe.**
There must be a way to change the code slightly by myself to make the program "flip" the video 90 degrees so it is rendered at 1920x1080

**Describe the solution you'd like**
I'm more than happy with someone just showing me where and what to change. Maybe in future releases include it in the .env file?

**Describe alternatives you've considered** (optional)
Honestly no clue. Not an expert in coding to be quite honest

**Additional context** (optional)

**Comment by CJthisis** [comment] 2022-06-26 10:46
This would require lots of testing (as a noob), because the size and position of the reddit screenshots would be all messed up, it think that is the hard part to get right.

**Comment by tayzuz** [comment] 2022-06-26 18:02
> This would require lots of testing (as a noob), because the size and position of the reddit screenshots would be all messed up, it think that is the hard part to get right.

Yup! I have very little coding knowledge so trying to change anything without fear of breaking the entire thing was stressful. Ultimately gave up because even when I found the line where the size of the video is specified, changing it to 1920x1080 did literally nothing. Don't get me wrong this tool is a life savior but a lot of the features are either sketchy as they threaten to break the entire thing or they just plainly don't work

**Comment by JasonLovesDoggo** [comment] 2022-06-26 19:18
Duplicate of #696

**Closed** 2022-06-26 19:18 UTC
Labels: enhancement
