### ISSUE TITLE
Consistent timeout error when lauching headless browser

### ISSUE THREAD

**Issue by ishaw18** [elebumm/RedditVideoMakerBot#185] opened 2022-06-03 01:34 UTC
I have consistently had an issue at this point in the program. I implemented a change of adding timeout = 0 in line 26 of screenshot downloader, and I did get one video to work, however I still face this issue 99% of the time.

the window as follows. Anyone know what's going on and how to fix this?
![image](https://user-images.githubusercontent.com/106784865/171769851-b6c3347b-4eb0-488f-b516-bd038a382dc1.png)

**Comment by nizarbamida** [comment] 2022-06-03 03:38
You can try disabling timout, or setting a higher value
```
# Get the thread screenshot
        page = browser.new_page()
        page.goto(reddit_object["thread_url"], timeout = 0)
```
or you can do it globaly using 
`page.set_default_timeout()`

**Comment by ishaw18** [comment] 2022-06-03 03:40
> You can try disabling timout, or setting a higher value
> 
> ```
> # Get the thread screenshot
>         page = browser.new_page()
>         page.goto(reddit_object["thread_url"], timeout = 0)
> ```
> 
> or you can do it globaly using `page.set_default_timeout()`

If you were to do it globally, where exactly do you do that? Within the sceenshot downloader script?

**Comment by nizarbamida** [comment] 2022-06-03 04:01
here 
```
        # Get the thread screenshot
        page = browser.new_page()
        page.set_default_timeout(0)
        page.goto(reddit_object["thread_url"])
```

**Comment by reinkdesigns** [comment] 2022-06-03 15:00
so i added this, and not the script just stops on Launching Headless Browser...
i let it sit for 10 minutes and nothing happened
![image](https://user-images.githubusercontent.com/104669790/171879917-75bcdc8e-d48a-4a1f-849d-2724355639cd.png)

yes i understand that removing the script time out was going to cause this, but why is the script hanging up on other subreddits, and how do we fix it?

**Comment by FireHe4d** [comment] 2022-06-05 21:59
same issue with timeout. Tried @nizarbamida method but it takes too long

**Comment by reinkdesigns** [comment] 2022-06-07 04:51
i tried letting it run for 8 hours while i slept and it never got past launching headless browser, does anyone have an idea whats causing it to lock up?

**Comment by ishaw18** [comment] 2022-06-07 04:58
I believe it most likely has something to do with how many/how long the comments are on the particular reddit thread. I think that it may just be going through for too long and then get tripped up. As far as a solution.. I am not sure.

**Comment by DylanDelobel** [comment] 2022-06-10 18:35
Duplicate of #34

**Comment by BinayakBishnu** [comment] 2022-06-15 03:32
It is possible that it was trying to load some image/video/link in the post or the comments
Happening to me right now

**Closed** 2022-07-04 23:52 UTC
Labels: bug, playwright
