### ISSUE TITLE
It won't let me make videos

### ISSUE THREAD

**Issue by MichaelBest01** [elebumm/RedditVideoMakerBot#904] opened 2022-07-08 16:00 UTC
**Describe the bug**
`Traceback (most recent call last):
  File "C:\Users\solod\Downloads\RedditVideoMakerBot-master\main.py", line 59, in <module>
    run_many(int(getenv("TIMES_TO_RUN")))
  File "C:\Users\solod\Downloads\RedditVideoMakerBot-master\main.py", line 49, in run_many
    main()
  File "C:\Users\solod\Downloads\RedditVideoMakerBot-master\main.py", line 37, in main
    length, number_of_comments = save_text_to_mp3(reddit_object)
  File "C:\Users\solod\Downloads\RedditVideoMakerBot-master\video_creation\voices.py", line 49, in save_text_to_mp3
    return text_to_mp3.run()
  File "C:\Users\solod\Downloads\RedditVideoMakerBot-master\TTS\engine_wrapper.py", line 65, in run
    self.call_tts(f"{idx}", comment["comment_body"])
  File "C:\Users\solod\Downloads\RedditVideoMakerBot-master\TTS\engine_wrapper.py", line 93, in call_tts
    self.tts_module.run(text=process_text(text), filepath=f"{self.path}/{filename}.mp3")
  File "C:\Users\solod\Downloads\RedditVideoMakerBot-master\TTS\GTTS.py", line 15, in run
    tts = gTTS(text=text, lang=os.getenv("POSTLANG") or "en", slow=False)
  File "C:\Users\solod\AppData\Local\Programs\Python\Python310\lib\site-packages\gtts\tts.py", line 134, in __init__
    assert text, "No text to speak"
AssertionError: No text to speak`

**To Reproduce**
Steps to reproduce the behavior: I just run python `main.py`

**Expected behavior**
A clear and concise description of what you expected to happen: I expected it to produce the videos. It used to work perfectly fine until I restarted my computer

**Screenshots**
![image](https://user-images.githubusercontent.com/60488290/178028454-cc66ca9d-bbe4-4930-8259-daf7d502b5a4.png)

**System (please complete the following information):**

- Python Version: Python 3.10
- OS: Windows 10
- App version / Branch: latest
**Additional context**

**Comment by William9923** [comment] 2022-07-09 01:34
thx for informing us related to this issue. We will be checking this issue. Will let you know once we found the problem 🙏

**Comment by MichaelBest01** [comment] 2022-07-09 02:41
After not turning on my laptop for a couple hours and not running the script it finally started to work again. I don't know what happened

**Comment by William9923** [comment] 2022-07-09 07:53
I don't think its about your computer. After a couple hours, it probably change the random thread. We will investigate these issues. Thx 🙏

**Comment by JasonLovesDoggo** [comment] 2022-07-12 05:16
Fixed In 2.3

**Comment by JasonLovesDoggo** [comment] 2022-07-12 05:17
It was caused by the text split function

**Closed by JasonLovesDoggo** 2022-07-12 05:17 UTC
Labels: bug, tts, error
