### ISSUE TITLE
Any way to make the bot accept cookies for longer comments?

### ISSUE THREAD

**Issue by Reiizov** [elebumm/RedditVideoMakerBot#211] opened 2022-06-03 16:10 UTC
Any way to accept cookies, so for longer comments it doesnt show this popup?
![image](https://user-images.githubusercontent.com/69767798/171904144-90cb1d0b-980d-4aae-b40a-0236fa43b419.png)

**Comment by LukaHietala** [comment] 2022-06-03 16:16
At the moment, we don't have any solutions to that. I may have a possible solution. Just go to Reddit with your account and accept the cookies manually.

**Comment by Reiizov** [comment] 2022-06-03 16:20
@LukaHietala Reddit doesn't ask me to accept cookies manually...

**Comment by FreebieII** [comment] 2022-06-03 16:30
> 




> @LukaHietala Reddit doesn't ask me to accept cookies manually...

Please refer to #39 or [Click Here](https://github.com/elebumm/RedditVideoMakerBot/issues/39#issuecomment-1143431528)

I will close this Issue as a duplicate of #39 , but feel free to re-open it if this does not solve your issue.

**Closed by FreebieII** 2022-06-03 16:30 UTC

**Comment by mlvps** [comment] 2022-06-15 15:25
> > 
> 
> > @LukaHietala Reddit doesn't ask me to accept cookies manually...
> 
> Please refer to #39 or [Click Here](https://github.com/elebumm/RedditVideoMakerBot/issues/39#issuecomment-1143431528)
> 
> I will close this Issue as a duplicate of #39 , but feel free to re-open it if this does not solve your issue.

it doesnt work for longer comments/ submissions
