### ISSUE TITLE
Getting this Error AFTER the video is being finished in the Bot. 

### ISSUE THREAD

**Issue by hakupila** [elebumm/RedditVideoMakerBot#776] opened 2022-07-01 06:28 UTC
Hello Guys

So after preparing everything and after the video is being made from the bot it does not appear in the results. Instead after the loading I am getting this Error instead the of the finished video:

Edit: I can also see all the raw material in the assets. The Bot just has trouble finishing the final video and putting it to the results.

![41dddc277f74a96bb9f775e491693e31](https://user-images.githubusercontent.com/108199354/176837099-3676fbfc-a057-41c2-9e98-09d8e935cf15.png)

Any ideas?

**Comment by ehroiecfert** [comment] 2022-07-01 08:03
I'm no expert but try:

run `pip install -r requirements.txt` again. 
Delete the assets folder.
Try to start the bot again.

**Comment by hakupila** [comment] 2022-07-01 08:08
> 

Thank you for your answer. When im re-running pip install -r requirements.txt I am getting everything besides something that can not be installed:

![2](https://user-images.githubusercontent.com/108199354/176852981-fff781ef-f4d2-4c7d-9833-2458356a1ea4.png)

**Comment by ehroiecfert** [comment] 2022-07-01 08:12
You don't have the right requirements... I'm not sure what exactly the problem is
Did your bot ever work?

**Comment by hakupila** [comment] 2022-07-01 08:13
Yes it worked perfectly for a few days

**Comment by ehroiecfert** [comment] 2022-07-01 08:21
My last ideas:
 1. Try to get the latest requirements.txt from repo. Then run the pip install command from above again. 
 
It's strange that the C++ tools are missing.
But if I run `pip list` to get all packages I don't even have the typed-ast

**Comment by ehroiecfert** [comment] 2022-07-01 08:32
The only thing that I mention that requests ist 2.28.0 instead of 2.28.1
So try `pip install requests==2.28.1`
After that, I have no clue what the problem is

**Comment by hakupila** [comment] 2022-07-01 09:04
I was able to install something when running pip install requests==2.28.1 

![dasdasdas](https://user-images.githubusercontent.com/108199354/176862906-c9fe4835-8993-4456-8a8a-88a77704396f.png)

Afterwards everything went smooth as usual, the video was loading and boom:

![sds](https://user-images.githubusercontent.com/108199354/176863055-17090b56-f87e-462e-a201-8d3310479a84.png)

**Comment by JasonLovesDoggo** [comment] 2022-07-05 00:02
Should be fixed in the newest version might not though It's caused by FFMPEGs handling of filenames

**Closed** 2022-07-06 05:44 UTC
