### ISSUE TITLE
Error in launching headless browser

### ISSUE THREAD

**Issue by VizVone** [elebumm/RedditVideoMakerBot#366] opened 2022-06-07 14:29 UTC
![unknown](https://user-images.githubusercontent.com/104826377/172405938-f1f1318d-48c9-4b6c-8d41-3c342198bc64.png)

**Comment by Tudorhc5** [comment] 2022-06-07 16:18
Did you do "playwright install" and "playwright install-deps" ?

**Comment by VizVone** [comment] 2022-06-07 16:25
Did Both but still the same issue

**Comment by HallowedDust5** [comment] 2022-06-08 01:37
I also got this issue after running those commands. The readme says that playwright should install automatically, but it didnt for me and honestly, idk what playwright is.

**Comment by Mhdtarek** [comment] 2022-06-08 05:29
Playwright is a headless browser used to screenshot the comments that's why the bot needs your username and password.

Make sure you have nodejs installed that could be your problem

**Comment by HallowedDust5** [comment] 2022-06-10 15:10
Ya I got it figured out afterwards. For anyone else, I installed nodejs and npm. Then I npx or npm (i dont remember which) installed playwright and then it worked from there.

**Comment by DylanDelobel** [comment] 2022-06-10 18:33
Duplicate of #34

**Comment by FreebieII** [comment] 2022-06-10 18:34
Closing as duplicate of [34](https://github.com/elebumm/RedditVideoMakerBot/issues/34)

Happy Coding!

**Closed by FreebieII** 2022-06-10 18:34 UTC
