### ISSUE TITLE
Not generating sound for contents of post

### ISSUE THREAD

**Issue by Venu2HD** [elebumm/RedditVideoMakerBot#1149] opened 2022-08-11 07:27 UTC
**Describe the bug**
Only sound for the title is being generated, I am getting no sound for the contents of the current post.

**To reproduce**
Generate a video with a subreddit such as r/TIFU, only the title will be read out loud.

**Expected behavior**
The bot would read the title of the post first, then read the post itself.

**Output**
https://youtube.com/shorts/ohq2Y3RCBWs

**System:**
- Python Version: Python 3.10
- OS: Windows 10
- App version: 2.4.2

**Comment by swoker** [comment] 2022-08-11 09:45
probably duplicate of https://github.com/elebumm/RedditVideoMakerBot/issues/1147
have you tried setting `storymode=true` in `config.toml`? That should be exactly hat you're looking for

**Comment by JasonLovesDoggo** [comment] 2022-08-12 00:40
That's because the bot isn't designed to do that.

**Closed** 2022-08-12 00:40 UTC
Labels: bug
