### ISSUE TITLE
Make the bot read the description of the post 

### ISSUE THREAD

**Issue by Foxcer11** [elebumm/RedditVideoMakerBot#905] opened 2022-07-08 16:17 UTC
The bot doesn't read the description of the post and skips straight ahead to the comments.

This could allow subreddits that almost always have a description to its post.

**Comment by William9923** [comment] 2022-07-09 01:35
Hi, could you give us more detail, like what part of the reddit comment want to be included (screenshot the description part might be helpful). Thanks 🙏

**Comment by AdmiralAtomic** [comment] 2022-07-09 13:06
> Hi, could you give us more detail, like what part of the reddit comment want to be included (screenshot the description part might be helpful). Thanks 🙏

I believe they mean the actual post content. At the moment the bot grabs the title of the thread and then goes straight to the comments. This wouldnt work on reddits such as nosleep or AITA as the posts content is in the post itself, not the title or the comments

**Comment by Foxcer11** [comment] 2022-07-09 14:59
> > Hi, could you give us more detail, like what part of the reddit comment want to be included (screenshot the description part might be helpful). Thanks 🙏
> 
> I believe they mean the actual post content. At the moment the bot grabs the title of the thread and then goes straight to the comments. This wouldnt work on reddits such as nosleep or AITA as the posts content is in the post itself, not the title or the comments

exactly how Admiral Atomic explained it, here's an example to further eloporate 

https://user-images.githubusercontent.com/69968700/178111158-12f7784c-39d5-4ec5-9ea4-7eb95f230195.mp4

**Comment by JasonLovesDoggo** [comment] 2022-07-10 01:45
Duplicate of like 40 different issues

**Comment by JasonLovesDoggo** [comment] 2022-07-10 01:45
It's called story mode and it's queued

**Comment by Foxcer11** [comment] 2022-07-10 10:35
> It's called story mode and it's queued

it's not storymode 

correct me if I am wrong , but story mode only reads the post and the description. not the comments

the thing I am suggesting is for the bot to read everything in the post  title; description; and comments

**Comment by JasonLovesDoggo** [comment] 2022-07-10 18:35
> > It's called story mode and it's queued
> 
> it's not storymode 
> 
> correct me if I am wrong , but story mode only reads the post and the description. not the comments
> 
> the thing I am suggesting is for the bot to read everything in the post  which is title; description; and comments

Give me a couple practical uses of that.

**Comment by Foxcer11** [comment] 2022-07-10 18:58
It's like the common thing for a reddit post to have a description, without the description the meaning behind the post would be cuttoff/limited. 

look at the subreddit called LifeProTips; most of its information is in the description of the post and not the title. with how the bot reads the post, the watcher wouldn't fully understand the post, as the title isn't enough the explain what the tip is but rather gives a general idea, but the description is the main focus behind the post. (More examples include YouShouldKnow, explainlikeimfive, CasualConversation, Lightbulb and much more.)

The way the bots works makes it that the post with only question-based posts that can utilized.

Yes, this sounds like story mode, but it's not; it's like the normal mode, but the description of the post is also included and read

**Comment by JasonLovesDoggo** [comment] 2022-07-10 19:26
Okay I guess I could implement that AFTER story mode

**Comment by Foxcer11** [comment] 2022-07-10 19:29
> Okay I guess I could implement that AFTER story mode

Take your time

**Comment by bobshepard87** [comment] 2022-09-22 22:40
I would like this as well.

**Closed** 2023-01-04 21:33 UTC
Labels: enhancement, keep

**Comment by bLaZeBeCoding** [comment] 2024-10-08 12:05
did this get fixed?
