### ISSUE TITLE
Suggestion: ignore links in text to speech

### ISSUE THREAD

**Issue by benjables** [elebumm/RedditVideoMakerBot#284] opened 2022-06-04 20:17 UTC
I just want to begin by saying this is an amazing feat of technology and thank you so much for making it! However, I just have one issue with it, whenever there is a link of some kind, it reads out the entire thing. Maybe some ways to counteract this issue is to check if a word begins with "www" or "https", and if it does, ignore it? Idk, I just thought it might make things better

**Comment by JasonLovesDoggo** [comment] 2022-06-05 00:56
Hmm you could use regex to find words with those tokens and simply just remove them from the TTS queue

**Comment by null3000** [comment] 2022-06-05 14:34
Done. Wrote a new PR. PR [311 ](https://github.com/elebumm/RedditVideoMakerBot/pull/311).

**Comment by CallumIO** [comment] 2022-06-05 20:10
Duplicate of #94 
Thanks for the bug report :D

**Closed** 2022-06-22 20:44 UTC
Labels: bug, enhancement
